<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gracias por tu compra_attachment-medium_a68d76</name>
   <tag></tag>
   <elementGuidId>00757bc9-7165-4823-b51e-2b2082e8b01f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium_large.size-medium_large.wp-image-845.entered.litespeed-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>21e16159-6f9d-44ab-8aea-483e140b4424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazyloaded</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4ea3936-b457-4cd6-adcb-46eae8b708df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-resp</name>
      <type>Main</type>
      <value>768x513</value>
      <webElementGuid>6d21a82f-b457-4b7f-acdb-43a1e797eb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-768x513.jpg</value>
      <webElementGuid>9cd73df3-2e51-47aa-ab97-9c5afad81a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>78ce251d-58f2-4aa8-9a31-dee5747dd037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>768</value>
      <webElementGuid>8524f1ea-8191-411e-84a8-e6194abf8c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>513</value>
      <webElementGuid>5ed36d99-b443-458f-a3fb-f0c924e41155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-768x513.jpg</value>
      <webElementGuid>c42abc44-c0fc-4bfb-9781-0deb805355a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium_large size-medium_large wp-image-845 entered litespeed-loaded</value>
      <webElementGuid>0d17589f-fd9f-42b6-addf-58b5b13c0bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-768x513.jpg 768w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-300x200.jpg 300w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-1024x684.jpg 1024w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-1536x1025.jpg 1536w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-2048x1367.jpg 2048w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-600x401.jpg 600w</value>
      <webElementGuid>17226e7f-5f92-4168-81df-01b5f2d3315b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>(max-width: 768px) 100vw, 768px</value>
      <webElementGuid>e06bcbc5-0f33-45a1-a41a-721db32effaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>1b145649-e2d8-44f1-b5e1-2c8a1e0aac85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 768px) 100vw, 768px</value>
      <webElementGuid>17d9870d-f175-4638-b6d7-111e6c0f0061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-768x513.jpg 768w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-300x200.jpg 300w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-1024x684.jpg 1024w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-1536x1025.jpg 1536w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-2048x1367.jpg 2048w, https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-600x401.jpg 600w</value>
      <webElementGuid>29a0ea5f-804c-402d-b0ba-bb456b0ca486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-841 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;elementor elementor-841&quot;]/div[@class=&quot;elementor-element elementor-element-76de804 e-flex e-con-boxed e-con&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-acfdf58 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-medium_large size-medium_large wp-image-845 entered litespeed-loaded&quot;]</value>
      <webElementGuid>3039a891-1baa-4c46-aba6-0fdbcd497a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/div/div[2]/div/img</value>
      <webElementGuid>f5113bde-b52c-4ea7-b9b5-ebb6d61ad612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-768x513.jpg')]</value>
      <webElementGuid>e942b8a8-2283-42bb-9080-7fa02afdfe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>f3b6abe6-823c-4e23-be15-b0d18f9ab453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pruebasqafenix.com/wp-content/uploads/2023/06/pexels-leeloo-thefirst-6675832-768x513.jpg']</value>
      <webElementGuid>a5ea46b6-5dc1-4be1-b61b-d1507ae0b49b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
