<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Realizar el pedido</name>
   <tag></tag>
   <elementGuidId>4b9de9e4-e5b2-4321-a072-23ab7a8073f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='place_order']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#place_order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d382479-612d-4891-80d2-d216702c89dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>55366ebf-b077-4d80-8fe9-a49d1605a6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alt</value>
      <webElementGuid>367d918b-4ebb-4be1-8f0a-37172d831c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>woocommerce_checkout_place_order</value>
      <webElementGuid>c81fa459-a0b2-4bde-b4f3-524c390b71f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>place_order</value>
      <webElementGuid>a3f900b8-4898-4778-9a43-56ec817696b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Realizar el pedido</value>
      <webElementGuid>027758a3-b551-4ddb-af4d-58cac6290cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Realizar el pedido</value>
      <webElementGuid>e7a192a6-632b-4808-a077-29368dc28934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Realizar el pedido</value>
      <webElementGuid>10df7d05-0ad4-4ef7-9d25-b0fe203a796c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;place_order&quot;)</value>
      <webElementGuid>9e4b59bb-9f78-4efe-b9f6-7485638c266a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='place_order']</value>
      <webElementGuid>2d1bf325-8d52-43b6-b852-cd30a83808ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/button</value>
      <webElementGuid>a66c4ec3-593d-40b1-8735-348f5f8f5ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(opcional)'])[1]/following::button[1]</value>
      <webElementGuid>748cf947-24c2-41e8-aa78-e4816af7ce20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscríbete al blog por correo electrónico'])[1]/preceding::button[1]</value>
      <webElementGuid>51dacfd6-c9a0-456b-9a08-90c2554a574d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirección de correo electrónico'])[1]/preceding::button[1]</value>
      <webElementGuid>9e7c0937-aa52-46c4-9188-032c3fa7585a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Realizar el pedido']/parent::*</value>
      <webElementGuid>b180a3d7-dddf-4ff4-aacd-70652d73a177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>c652872c-1b29-439e-a683-d37147e98286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'woocommerce_checkout_place_order' and @id = 'place_order' and (text() = 'Realizar el pedido' or . = 'Realizar el pedido')]</value>
      <webElementGuid>791c757c-a935-46b5-82ce-18030b0e2bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
