<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Tu pedido</name>
   <tag></tag>
   <elementGuidId>becfb532-a69c-4033-a5b1-c41b31738bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='order_review_heading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_review_heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>08adb46b-5dcd-4faa-8e51-9675e6c3ebe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_review_heading</value>
      <webElementGuid>a5fb0152-e532-4abc-9b87-bcd9ca685c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tu pedido</value>
      <webElementGuid>ea917620-ee0a-4fb7-8869-54c0aff4e234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_review_heading&quot;)</value>
      <webElementGuid>dc918318-0953-46bc-9aa1-44dfe6544bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='order_review_heading']</value>
      <webElementGuid>dc0e1a3b-324c-4240-b70d-2828aca99124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/div/div[2]/div/div/div/div/form[3]/h3</value>
      <webElementGuid>6c026a45-8b55-4006-b0e4-4a8477120668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::h3[1]</value>
      <webElementGuid>2f9878ac-d076-44c3-8aef-a68cad4c0326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto'])[1]/preceding::h3[1]</value>
      <webElementGuid>da1e64a2-5f2f-4fa3-ada9-301462f6b374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/preceding::h3[1]</value>
      <webElementGuid>db903c76-faff-46c5-a7cf-115d075274f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tu pedido']/parent::*</value>
      <webElementGuid>dcfa36b1-7e66-4e9f-9828-3298ebdd7693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/h3</value>
      <webElementGuid>6edbb982-f086-4097-a27e-9607f5162981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'order_review_heading' and (text() = 'Tu pedido' or . = 'Tu pedido')]</value>
      <webElementGuid>65698bc9-19cc-4794-8c48-99f56286a19b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
