<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suscrbete a nuestro boletn_ship_to_di_21497e</name>
   <tag></tag>
   <elementGuidId>48c54e27-e8ae-4be3-b0f5-70b7448b66a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ship-to-different-address-checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ship-to-different-address-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>621cd1f9-a7d9-4b95-8b65-8843c858cd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ship-to-different-address-checkbox</value>
      <webElementGuid>ad39c15b-fcbe-42ad-ae4b-b48f0019353f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>e740c0da-6dc8-47f6-b96b-0a95c61cdbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>fcd82192-693b-4cb7-9a04-f9c2396d0f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c2f6e135-2119-4023-bf21-21ec693e3f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ship_to_different_address</value>
      <webElementGuid>2ded4269-1167-4de3-adc9-f17e4dd2c8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ffb7620d-4435-413a-abf2-8d48bcb81aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ship-to-different-address-checkbox&quot;)</value>
      <webElementGuid>b2bcb066-a1cc-49ac-966e-de213194fdde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ship-to-different-address-checkbox']</value>
      <webElementGuid>c6a714eb-dadf-4518-9ff1-3634f5028c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='ship-to-different-address']/label/input</value>
      <webElementGuid>0178169d-d397-4cc3-a4e9-d88175f6a177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/label/input</value>
      <webElementGuid>e9086e41-9630-417d-b333-5d1ec2bc1f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ship-to-different-address-checkbox' and @checked = 'checked' and @type = 'checkbox' and @name = 'ship_to_different_address']</value>
      <webElementGuid>c345cf4b-1abf-40af-91bf-03e7feb13bde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
