<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marca aqu para recibir la invitacin de_4e7bcb</name>
   <tag></tag>
   <elementGuidId>6733c592-df17-4d77-8a19-c451fd75cc3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment']/div/div/p/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.woocommerce-terms-and-conditions-checkbox-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f4a9ad8-a2e7-4eca-b235-a96d4c3b2d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-terms-and-conditions-checkbox-text</value>
      <webElementGuid>0dafa790-dc7d-4ea3-b4ec-988cd80018a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marca aquí para recibir la invitación de CusRev (una organización de terceros independiente) para valorar tu pedido</value>
      <webElementGuid>e8e400c0-b401-4cd3-938c-c444571636dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment&quot;)/div[@class=&quot;form-row place-order&quot;]/div[@class=&quot;woocommerce-terms-and-conditions-wrapper&quot;]/p[@class=&quot;cr-customer-consent&quot;]/label[@class=&quot;woocommerce-form__label woocommerce-form__label-for-checkbox checkbox&quot;]/span[@class=&quot;woocommerce-terms-and-conditions-checkbox-text&quot;]</value>
      <webElementGuid>ccb33bd9-8ea8-416e-8b92-784a27cc2084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/div/p/label/span</value>
      <webElementGuid>15c38921-a19b-4055-a0c6-cf1edb30ebbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contáctenos en {email} para preguntas relacionadas con reembolsos y devoluciones.'])[1]/following::span[1]</value>
      <webElementGuid>0fa66194-8012-410a-b97b-6a3ad1aaacaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Necesitas ayuda?'])[1]/following::span[1]</value>
      <webElementGuid>96b7eec1-da62-48ab-9469-9f3d3b66b126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='términos y condiciones'])[1]/preceding::span[1]</value>
      <webElementGuid>eeca2937-4f39-4d13-884e-d8ed0a5f7b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marca aquí para recibir la invitación de CusRev (una organización de terceros independiente) para valorar tu pedido']/parent::*</value>
      <webElementGuid>58dcc78b-1127-420e-9b08-1d1c44223068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p/label/span</value>
      <webElementGuid>68fa0485-3a8b-4189-968f-e949abc4a41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Marca aquí para recibir la invitación de CusRev (una organización de terceros independiente) para valorar tu pedido' or . = 'Marca aquí para recibir la invitación de CusRev (una organización de terceros independiente) para valorar tu pedido')]</value>
      <webElementGuid>89f62323-9751-406d-af78-2f2c3cffb69f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
