<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CiudadDelEnvio</name>
   <tag></tag>
   <elementGuidId>06117d58-65b7-4d31-89a1-eab9e4ccd8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calc_shipping_city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calc_shipping_city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9629ed2-29e8-46f0-907b-8e6205d87293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9690f47f-7077-4b52-90f7-2ed694443cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>75dcccff-aa5a-4685-96b9-a0632d5d7f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ciudad</value>
      <webElementGuid>b9a8489d-ad23-45fd-a7ad-1e4f68593f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_shipping_city</value>
      <webElementGuid>9af0341d-bbdf-4430-b31e-10f78fd8de63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calc_shipping_city</value>
      <webElementGuid>ea02400e-bc88-47e2-825e-dc18a937be3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calc_shipping_city&quot;)</value>
      <webElementGuid>6b2efdef-cba4-4846-933d-0ae27cadcfb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calc_shipping_city']</value>
      <webElementGuid>9f8c3ccd-8893-4bf5-a2cf-fbaa7f51cb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_city_field']/input</value>
      <webElementGuid>684664f0-1bd1-4e1a-9afc-32f4278a11dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/p[3]/input</value>
      <webElementGuid>a1a84042-620e-4d78-acfa-34a954fe905c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ciudad' and @name = 'calc_shipping_city' and @id = 'calc_shipping_city']</value>
      <webElementGuid>78207e15-33ad-4347-87ae-43bd8faa5109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
