<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CPDelEnvio</name>
   <tag></tag>
   <elementGuidId>b2a2ad7b-fb5a-480d-9e78-7f3cf25088d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calc_shipping_postcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calc_shipping_postcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa9bdde4-fa0e-42d0-bbf5-e4933160e5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34d7e20f-3241-47e9-b457-c3f9b62f5f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>c8367407-fcad-4e45-9760-175947c3d495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código postal</value>
      <webElementGuid>ef6866a9-8cf5-43aa-b614-ee8b813e076e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_shipping_postcode</value>
      <webElementGuid>1780c411-43a4-4139-b31c-74bfd5f52e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calc_shipping_postcode</value>
      <webElementGuid>24a144a2-e058-4494-9d3f-d7b784fc49a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calc_shipping_postcode&quot;)</value>
      <webElementGuid>f8998dca-e768-4443-ac36-6417c32c6023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calc_shipping_postcode']</value>
      <webElementGuid>2135fe98-67b4-4e80-bcc4-9533a99bad21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_postcode_field']/input</value>
      <webElementGuid>27e6c0d2-6b99-455c-bbf3-6ad0f7b960aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>41fc820b-faca-4dc7-9a32-ab51b61d6c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Código postal' and @name = 'calc_shipping_postcode' and @id = 'calc_shipping_postcode']</value>
      <webElementGuid>dc233b52-fa03-427b-8c6e-12fa460a334b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
