<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Precio fijo 3,00</name>
   <tag></tag>
   <elementGuidId>669cf123-79ac-44be-bccc-cb4e076d8cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='shipping_method']/li/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>65d2e8f1-249d-45ba-abb9-59d2494f3480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>shipping_method_0_flat_rate2</value>
      <webElementGuid>4df49d7a-0801-4dd5-bb1e-b98178ba60eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Precio fijo: 3,00 €</value>
      <webElementGuid>c68fbcbc-ddec-48b6-8010-2e2835c2e885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping_method&quot;)/li[1]/label[1]</value>
      <webElementGuid>1e8ad038-51ea-413e-a961-40522d3b56cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='shipping_method']/li/label</value>
      <webElementGuid>97441ea8-bda1-4b7f-b576-c124160c0888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envío'])[1]/following::label[1]</value>
      <webElementGuid>24844cee-18a3-4bc5-b810-267a6ea4c99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[4]/following::label[1]</value>
      <webElementGuid>683f9b03-c6ce-4833-a1e1-471204d2cf9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País o región:'])[1]/preceding::label[1]</value>
      <webElementGuid>2eb84b70-1544-4fe1-82ee-23d155e75d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Precio fijo:']/parent::*</value>
      <webElementGuid>9d5551cc-901d-458f-8d97-8ed93956fdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/label</value>
      <webElementGuid>3b537921-6ea4-48ca-866d-54e93cd5fb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Precio fijo: 3,00 €' or . = 'Precio fijo: 3,00 €')]</value>
      <webElementGuid>70d017e6-5532-4553-a595-a9c0ae90702c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
