<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Espaa</name>
   <tag></tag>
   <elementGuidId>a460073a-e2ae-45f7-beba-f6cdfa47c579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-calc_shipping_country-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='select2-selection__rendered'][contains(@id,'country-container')][contains(.,'España')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15e82437-1f6f-4975-929f-cb87381b6fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>cf5bb765-d5f0-4d39-acf4-7e12ea420ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-calc_shipping_country-container</value>
      <webElementGuid>c293fc44-652c-4a3e-a0e0-a543635f3f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3174873d-2656-435e-8449-b7b9583f0284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6040a1e-056a-4fdb-8cdd-e28c455f11a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>España</value>
      <webElementGuid>def3ede2-0bff-46cb-bdbc-0336a50dc0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>España</value>
      <webElementGuid>797a830a-b6b3-42e5-a79b-c2894d7f0af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-calc_shipping_country-container&quot;)</value>
      <webElementGuid>ce738760-8ef7-4d7d-a35b-6f20741ee5fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-calc_shipping_country-container']</value>
      <webElementGuid>ae2f3a88-d8f5-4a2c-b426-34012a6ce565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_country_field']/span/span/span/span</value>
      <webElementGuid>74d46d16-47be-487b-854e-8674efa0f90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País o región:'])[1]/following::span[4]</value>
      <webElementGuid>6723428a-2dd8-4dcf-8f7d-0312d5fb85eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[5]/following::span[4]</value>
      <webElementGuid>3e485fb3-ecc4-44c6-833b-ae3895680e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::span[3]</value>
      <webElementGuid>152a6f80-3f33-400b-8bf2-3f1a6178af8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>42e6f663-8a05-44f0-80e1-019cee88bea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-calc_shipping_country-container' and @title = 'España' and (text() = 'España' or . = 'España')]</value>
      <webElementGuid>af55c8b1-3228-41ce-9c5a-44340c454e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
