<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Regin  Provincia</name>
   <tag></tag>
   <elementGuidId>edab88cf-3247-4125-ba44-2438e42cba5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-calc_shipping_state-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='select2-selection__rendered'][contains(@id,'state-container')][contains(.,'Madrid')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b40ad126-5ca9-46a5-a0f9-84735e062e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>20f253d2-5adf-4702-9b76-be3335e560ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-calc_shipping_state-container</value>
      <webElementGuid>0e1c0425-e01a-4abe-9d76-0ba6b02f95f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b3082bca-df5b-4820-bdb0-8b4af866aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d755aeca-448f-4735-a89b-fd60f12312fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Región / Provincia</value>
      <webElementGuid>6e18b650-25b2-4e8d-80ca-b3281cd5ac52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-calc_shipping_state-container&quot;)</value>
      <webElementGuid>d35a9396-0e35-48ee-ad70-cd706359a0e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-calc_shipping_state-container']</value>
      <webElementGuid>66f05b90-613a-4e7e-981e-7f64cd8ba3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_state_field']/span/span/span/span/span</value>
      <webElementGuid>08d5514c-3e14-4cd6-9477-fddd899b7e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>3822f19a-6c8f-4afc-8ce0-1101d127d28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>28c38b77-38e9-4565-87d9-b305c6f107fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-calc_shipping_state-container' and (text() = 'Región / Provincia' or . = 'Región / Provincia')]</value>
      <webElementGuid>588b9f89-52f2-4ad6-b6b5-2ca50099cc78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
