<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextoDeOpcionesDeEnvio</name>
   <tag></tag>
   <elementGuidId>a29a2c3f-02ea-49c7-8042-8cd8ea6e0b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div[4]/div/table/tbody/tr[2]/td/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-shipping-destination</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>38dbcfa8-ee2b-4005-bc9e-8aae0570c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-shipping-destination</value>
      <webElementGuid>88468f3f-fe07-4346-8964-933a27340871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Las opciones de envío se actualizarán durante el pago.				</value>
      <webElementGuid>bd7b3832-e1b0-45d6-8ab7-a98ff605ba2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;cart-collaterals&quot;]/div[@class=&quot;cart_totals&quot;]/table[@class=&quot;shop_table shop_table_responsive&quot;]/tbody[1]/tr[@class=&quot;woocommerce-shipping-totals shipping&quot;]/td[1]/p[@class=&quot;woocommerce-shipping-destination&quot;]</value>
      <webElementGuid>d6e21333-6b01-4e47-a59b-0158fc03d036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div[4]/div/table/tbody/tr[2]/td/p</value>
      <webElementGuid>f47d34d4-9cde-4513-8ff1-5530ff6a41c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[5]/following::p[1]</value>
      <webElementGuid>99c63b33-d447-41de-b883-f788bc8c0ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País o región:'])[1]/preceding::p[1]</value>
      <webElementGuid>49f51675-0d9e-4d85-92a6-b29fd1945968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Las opciones de envío se actualizarán durante el pago.']/parent::*</value>
      <webElementGuid>7192bc7f-3d31-4dd9-849b-4d348d16e48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/p</value>
      <webElementGuid>ad44766f-0bed-4f34-91f3-314d5cb834b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
					Las opciones de envío se actualizarán durante el pago.				' or . = '
					Las opciones de envío se actualizarán durante el pago.				')]</value>
      <webElementGuid>68c96c84-5f2e-4d94-938f-cac2fca38bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
