<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Producto</name>
   <tag></tag>
   <elementGuidId>32ea61f5-5d4a-47ad-95b4-3e44a4789fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/thead/tr/th[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.product-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>517f29d3-5fd2-40d9-8adb-21101531cf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>60d84d65-da7c-420b-b1f2-baf83c9c31b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Producto</value>
      <webElementGuid>698ad88b-a3af-4bb8-9e7a-9a0cee2d711e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/thead[1]/tr[1]/th[@class=&quot;product-name&quot;]</value>
      <webElementGuid>65dac901-148f-4c31-8431-1e920dedeab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/thead/tr/th[3]</value>
      <webElementGuid>1dfe8197-8633-4517-94e5-1ed1222a1d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagen en miniatura'])[1]/following::th[1]</value>
      <webElementGuid>a6c58a4c-c539-4aed-bdef-2bcec9d15bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar artículo'])[1]/following::th[2]</value>
      <webElementGuid>6c8fbee3-838c-497a-980e-9f62184baeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio'])[1]/preceding::th[1]</value>
      <webElementGuid>3727b65d-1274-4b5a-8155-d2591f4370ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[1]/preceding::th[2]</value>
      <webElementGuid>db764821-ada9-4118-8a32-1cc632d4b29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Producto']/parent::*</value>
      <webElementGuid>cf25b855-d3c7-44d7-9f65-bed67f7cf3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]</value>
      <webElementGuid>bbf455e8-7e6d-44a6-8ae2-36580dd7c32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Producto' or . = 'Producto')]</value>
      <webElementGuid>79cf8948-31db-4d96-9fec-0b11bd23bc5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
