<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_5f269b</name>
   <tag></tag>
   <elementGuidId>d6f6a2ba-a4cf-4ae9-bc61-0712202914ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr/td[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dda44eae-caca-4b68-a022-eee1fe89b30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>54780f3f-8984-44dd-8df2-082e08611888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>89679b1b-eff1-42e8-814c-160c38b556df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472-300x450.jpg</value>
      <webElementGuid>6b1a0513-0502-4b73-b924-a4c9cc3685a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>03e38be9-6ca6-4c57-b182-2082c2706383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pantalón de hombre</value>
      <webElementGuid>d7b8d5df-a6ad-48ba-8f94-5de704e3b7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>77ece4eb-5cb1-48e2-8005-cfc6e61f5932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472-300x450.jpg.webp 300w, https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472-600x900.jpg.webp 600w, https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472-200x300.jpg 200w, https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472-40x60.jpg.webp 40w, https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472.jpg.webp 640w</value>
      <webElementGuid>209c7fe1-5394-462e-9acd-cdb2f186fadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>fe31ecf4-ed04-45b3-a5f7-1ec2433e224c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-thumbnail&quot;]/a[1]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>5de5f445-18a7-40ab-99b2-c13e818b8319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>efd660dc-ffb7-49a0-a23c-c4763c777fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pantalón de hombre']</value>
      <webElementGuid>8d532177-10a1-4201-8773-00bdf7ed2f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/img</value>
      <webElementGuid>a7388c25-9723-471c-af22-d90188699465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pruebasqafenix.com/wp-content/uploads/2019/04/pexels-jt-kim-914472-300x450.jpg' and @alt = 'pantalón de hombre']</value>
      <webElementGuid>aa873538-7849-4cfc-9722-d48272313b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
