<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_5f269b_1</name>
   <tag></tag>
   <elementGuidId>d820f4ac-39af-4544-a1bb-8ee4cfc11f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr[2]/td[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a0e8da0-536f-4842-82e0-4c093575f8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>4b93893d-ed8e-41e1-ba54-510c228e41a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>4523e63d-39bd-4f8b-b282-3b9e6bf85501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-300x450.jpg</value>
      <webElementGuid>3ffa1f6c-7ce1-4a7c-9779-7f3b407f72d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>8d8c7ec4-a540-406e-9386-1990b9257dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e6fb32b2-712f-4900-9d17-618c285d5f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-300x450.jpg.webp 300w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-600x900.jpg.webp 600w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-200x300.jpg.webp 200w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-682x1024.jpg.webp 682w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-768x1152.jpg.webp 768w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-40x60.jpg.webp 40w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280.jpg.webp 853w</value>
      <webElementGuid>2826ee0d-8370-45a8-835a-c97e267f859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>693be5f7-1c1f-4667-b013-8de20ec58717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-thumbnail&quot;]/a[1]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>789019e4-4ae6-4a7b-895d-eaab50e2f255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr[2]/td[2]/a/img</value>
      <webElementGuid>f6f39962-c0cd-403b-984b-6f5e8998f637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-300x450.jpg')]</value>
      <webElementGuid>941777c9-e42c-4678-ab79-618e6f6b0f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a/img</value>
      <webElementGuid>d7ebb750-b956-4cd6-91c7-35683bbe6cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-5916565_1280-300x450.jpg']</value>
      <webElementGuid>6d5937f3-3a56-4fab-a415-52cf3329dcf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
