<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Jenkins</name>
   <tag></tag>
   <elementGuidId>779c2c47-3942-41a8-846d-b132eca78380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginIntroDefault']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Jenkins logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>30752b17-a8ac-4827-81af-5a6e3b8f9c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/960ae89e/images/svgs/logo.svg</value>
      <webElementGuid>981db4c5-3457-47ae-9195-bac4d036d232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jenkins logo</value>
      <webElementGuid>4d080b69-255f-4356-9647-b63533d0ed9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginIntroDefault&quot;)/div[@class=&quot;logo&quot;]/img[1]</value>
      <webElementGuid>61bba876-016c-487b-b566-04c65afab4d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginIntroDefault']/div/img</value>
      <webElementGuid>e10fa4a6-e272-47f7-ba0a-31ae7096a196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Jenkins logo']</value>
      <webElementGuid>c49d3067-94de-4f96-94b9-3df5ed73b348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>691a6912-6b9d-4068-8acc-b5d4bef1f2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/960ae89e/images/svgs/logo.svg' and @alt = 'Jenkins logo']</value>
      <webElementGuid>3772d026-f2b0-41b9-a057-3f51536c32de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
