<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Desconectar</name>
   <tag></tag>
   <elementGuidId>8dc32f46-85bb-4340-b1ba-d39a14379298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d54b89c-3cdb-43e1-8766-bab808973b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout</value>
      <webElementGuid>51dc2fc6-95dc-4ac1-a15a-5b92092afc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desconectar</value>
      <webElementGuid>7dafa985-2561-40b1-8d7d-95edfac882d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/div[@class=&quot;login page-header__hyperlinks&quot;]/a[2]</value>
      <webElementGuid>1a4e8f19-2f5d-46e7-9bee-b3296a033659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/div[3]/a[2]</value>
      <webElementGuid>83e24172-190a-4fd6-a37e-348bb4e4d2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alejandro canosa'])[1]/following::a[1]</value>
      <webElementGuid>042e3c2b-23de-4618-be45-eb6fb4285fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenkins'])[1]/following::a[4]</value>
      <webElementGuid>a96e410d-a8e3-4ff3-b8d5-d758a000722e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel de Control'])[1]/preceding::a[1]</value>
      <webElementGuid>ea23318f-9ca5-4e4f-a7d2-1ca58faebd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout')]</value>
      <webElementGuid>7ba94b01-db79-427f-ada3-66e1db24b32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>2557441d-9165-44e9-8553-03fa81ad413b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/logout' and (text() = 'Desconectar' or . = 'Desconectar')]</value>
      <webElementGuid>0cccc6c5-ebc0-45b7-9fad-416ae04f985d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
