<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Desconectar</name>
   <tag></tag>
   <elementGuidId>b7a63a06-e54b-458b-b948-fa69b291ca2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/div[3]/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > span.hidden-xs.hidden-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>69437b36-f5f9-4769-91b4-974fef7fa389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-xs hidden-sm</value>
      <webElementGuid>caeae203-13c6-491a-b9ef-7cd83c8fc6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desconectar</value>
      <webElementGuid>42aee72a-04dd-41d5-9a51-790e3ac74adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/div[@class=&quot;login page-header__hyperlinks&quot;]/a[2]/span[@class=&quot;hidden-xs hidden-sm&quot;]</value>
      <webElementGuid>45989508-0ba4-476a-997f-8ea443a3761e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/div[3]/a[2]/span</value>
      <webElementGuid>77b62986-b8dd-4e7a-b962-e5ba030bf365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alejandro canosa'])[1]/following::span[1]</value>
      <webElementGuid>332163f3-df61-4873-a1f3-f9b696a65d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenkins'])[1]/following::span[4]</value>
      <webElementGuid>4a9faec7-c87d-4572-bf76-254b89551afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel de Control'])[1]/preceding::span[1]</value>
      <webElementGuid>cbba9243-3236-46c5-bc6d-9d76d11f6ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva Tarea'])[1]/preceding::span[2]</value>
      <webElementGuid>0a403db1-57cc-415f-9862-a8c01804ccab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Desconectar']/parent::*</value>
      <webElementGuid>0f3a0dcd-5851-4b0c-aa89-1544d1931e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>e2738528-b3e2-4799-86b5-0e9670a1eaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Desconectar' or . = 'Desconectar')]</value>
      <webElementGuid>7a36fddc-21e7-44cb-947b-0fff758247b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
