<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ver carrito</name>
   <tag></tag>
   <elementGuidId>5ca499ab-dc4d-44f2-9535-d5fc6b63a350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/ul/li/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.added_to_cart.wc-forward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>301482b1-1082-46ed-998d-1790ad2adb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/carrito/</value>
      <webElementGuid>8aae9b04-55f4-468c-adfc-d27127ff23c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>added_to_cart wc-forward</value>
      <webElementGuid>51bdbf3b-0dae-40a0-a8b0-50eedb1bb471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver carrito</value>
      <webElementGuid>750224e8-a7d8-4624-8cdb-9b9a0719b295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver carrito</value>
      <webElementGuid>88084782-78b2-4859-8b28-1f102f85fe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-9&quot;]/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-565 status-publish first instock product_cat-descuento-50 product_cat-ropa product_cat-ropa-de-hombre product_tag-conjunto has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple yith-wcbm-product-has-badges&quot;]/a[@class=&quot;added_to_cart wc-forward&quot;]</value>
      <webElementGuid>60da1c99-1066-4864-8fa9-53667e92f98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/ul/li/a[3]</value>
      <webElementGuid>056a03c0-ef0d-48a6-aea2-e6fb933c141e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ver carrito')])[2]</value>
      <webElementGuid>49d61996-6401-49e2-95fa-589430a6b7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir al carrito'])[1]/following::a[1]</value>
      <webElementGuid>d2045fe2-ce2a-4a6c-a1aa-9bcc743a32cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[5]/following::a[2]</value>
      <webElementGuid>6b4a479d-3da9-4849-8ca6-3952806ce0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Oferta!'])[2]/preceding::a[2]</value>
      <webElementGuid>f8b5fcc8-9dfe-419e-b0a3-a43a1aedd295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vestido de noche'])[1]/preceding::a[2]</value>
      <webElementGuid>e53e16dd-3d94-43a1-9842-c8b4a38ab70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://pruebasqafenix.com/carrito/')])[4]</value>
      <webElementGuid>8399d168-dcd8-45e9-9284-177c78bd92d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>1a9dcddf-74a6-4e67-b5bd-9a01f4fe6e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://pruebasqafenix.com/carrito/' and @title = 'Ver carrito' and (text() = 'Ver carrito' or . = 'Ver carrito')]</value>
      <webElementGuid>dfabf599-cc70-494f-a501-c07b5c7633ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
