<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Oferta</name>
   <tag></tag>
   <elementGuidId>4b569475-d0e8-4f32-b0e7-94d9aefe0a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.onsale</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1bfac4b7-9a90-4cb8-a591-8e7799ff09de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onsale</value>
      <webElementGuid>b8b512ce-a56b-4c40-87da-0ddc86809476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Oferta!</value>
      <webElementGuid>d5490c5c-4444-455a-b444-bc825e801fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-9&quot;]/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-565 status-publish first instock product_cat-descuento-50 product_cat-ropa product_cat-ropa-de-hombre product_tag-conjunto has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple yith-wcbm-product-has-badges&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/span[@class=&quot;onsale&quot;]</value>
      <webElementGuid>12311f5b-7c1a-4d91-a109-115f2dbc8199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/ul/li/a/span</value>
      <webElementGuid>c438f244-4d2f-4ba6-aaf6-d10bc84b5861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados de búsqueda: “”'])[1]/following::span[1]</value>
      <webElementGuid>0dad9b56-3356-41ed-a5c2-f38160e80c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descuento 50%'])[1]/following::span[1]</value>
      <webElementGuid>a977533e-0034-4bc6-be10-0701809dec6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pantalón y camisa de hombre'])[1]/preceding::span[1]</value>
      <webElementGuid>4ed0bd0c-3c2f-44d6-9c1a-0e67d87ed0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/preceding::span[1]</value>
      <webElementGuid>15f52c32-8955-49d4-9c72-bccd7e03bab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Oferta!']/parent::*</value>
      <webElementGuid>d22e0756-6281-4467-96d7-ad2c7af3a4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/ul/li/a/span</value>
      <webElementGuid>3b3999dc-0379-44e0-94e8-bebcc0df6076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '¡Oferta!' or . = '¡Oferta!')]</value>
      <webElementGuid>bd841822-d16c-4412-b56d-ea64cf147ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
