<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonBuscar</name>
   <tag></tag>
   <elementGuidId>48393f8b-0f77-4e17-b7c4-01eb15305139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='second-site-navigation']/div/div/form/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.la.la-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>86dbbb16-34ac-4718-ae2e-37040dffc3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>la la-search</value>
      <webElementGuid>1ef27da5-c61f-4693-82c5-806c0c3ef6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e397abb-5c44-4abd-9ec0-2132f51efe57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;second-site-navigation&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-search-form&quot;]/form[1]/button[@class=&quot;header-search-button&quot;]/i[@class=&quot;la la-search&quot;]</value>
      <webElementGuid>face79df-ba45-403b-a921-a7f72aa3c23f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='second-site-navigation']/div/div/form/button/i</value>
      <webElementGuid>3f475215-e963-4989-b84e-6b3067fa85fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>67b9f3d7-fa0f-45eb-b215-e64f5005f32d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
