<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DesplegableCategorias</name>
   <tag></tag>
   <elementGuidId>1611e3a5-e915-470e-8ab7-fdddfa173aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='product_cat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;product_cat&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>658a32be-79f1-4e4f-9b9c-b8343cf1c4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-search-select</value>
      <webElementGuid>3e06df0e-9ad1-40cc-8c64-fae590868c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_cat</value>
      <webElementGuid>e5d86af6-00ab-4f41-b984-4537836b8489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Todas las categoríasAccesorios (12)Descuento 50% (4)Envío gratis (1)Nuevo (3)Ropa (16)Ropa de hombre (5)Ropa de mujer (11)Zapatos (3)                </value>
      <webElementGuid>cda32b5b-0285-43ce-a0ce-681bf0b4597b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;second-site-navigation&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-search-form&quot;]/form[1]/select[@class=&quot;header-search-select&quot;]</value>
      <webElementGuid>8dc33fc1-38e2-420f-83b8-f0ac303d08ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='product_cat']</value>
      <webElementGuid>3e84739d-06ea-47ce-980b-0ecdbe0426af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='second-site-navigation']/div/div/form/select</value>
      <webElementGuid>950a6156-a84d-4e9f-ad91-60fa64befe78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropa de hombre'])[1]/following::select[1]</value>
      <webElementGuid>1fd20dc4-36f0-4d6d-8632-49e01f9d1883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropa de mujer'])[1]/following::select[1]</value>
      <webElementGuid>4664163f-b07e-40ae-85c4-bb1f8f47723b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envio gratis'])[1]/preceding::select[1]</value>
      <webElementGuid>21935288-ee20-486e-afba-3c42cf85c607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas especiales'])[1]/preceding::select[1]</value>
      <webElementGuid>1161e794-d03f-4888-81b5-12ba796f3ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>83083d53-a959-467a-8acd-b8a1e1e63788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'product_cat' and (text() = 'Todas las categoríasAccesorios (12)Descuento 50% (4)Envío gratis (1)Nuevo (3)Ropa (16)Ropa de hombre (5)Ropa de mujer (11)Zapatos (3)                ' or . = 'Todas las categoríasAccesorios (12)Descuento 50% (4)Envío gratis (1)Nuevo (3)Ropa (16)Ropa de hombre (5)Ropa de mujer (11)Zapatos (3)                ')]</value>
      <webElementGuid>98e576a1-805f-42de-b580-ac95253b1749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
