<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancelar</name>
   <tag></tag>
   <elementGuidId>82d719f8-1801-422f-8edc-efe1f599685a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/table/tbody/tr[4]/td[5]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-button.button.cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c86c3f7-c4be-4e2e-9fbd-b56e6553f808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/carrito/?cancel_order=true&amp;order=wc_order_SSjUnF0eJVNYf&amp;order_id=838&amp;redirect=https%3A%2F%2Fpruebasqafenix.com%2Fmi-cuenta%2F&amp;_wpnonce=be2c19371b</value>
      <webElementGuid>4f1658fa-aced-433b-82b4-442b7810878a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-button button cancel</value>
      <webElementGuid>7bec4494-c4b3-48cf-975a-eca268a6a09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>17b5c8c2-26ff-4eeb-8a86-b57f7da3b061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-464 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/table[@class=&quot;woocommerce-orders-table woocommerce-MyAccount-orders shop_table shop_table_responsive my_account_orders account-orders-table&quot;]/tbody[1]/tr[@class=&quot;woocommerce-orders-table__row woocommerce-orders-table__row--status-pending order&quot;]/td[@class=&quot;woocommerce-orders-table__cell woocommerce-orders-table__cell-order-actions&quot;]/a[@class=&quot;woocommerce-button button cancel&quot;]</value>
      <webElementGuid>fcf1e080-3a80-4386-87e9-85e003a31948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/table/tbody/tr[4]/td[5]/a[3]</value>
      <webElementGuid>8a0c0cbd-845e-4d8b-9db4-f3b46e9df14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancelar')]</value>
      <webElementGuid>a5ef7f57-3485-48c1-a994-f4c0b2149d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver'])[4]/following::a[1]</value>
      <webElementGuid>d227a4cc-29a5-4fd2-8f0f-f056df5784e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagar'])[1]/following::a[2]</value>
      <webElementGuid>74731b3a-5e83-44cd-bb7a-df82e9dd843e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#831'])[1]/preceding::a[1]</value>
      <webElementGuid>b87c2995-04c2-45f1-b25b-bfd53a228043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendiente de pago'])[2]/preceding::a[2]</value>
      <webElementGuid>6cf18b10-bbbb-4777-8428-b4f290a27801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelar']/parent::*</value>
      <webElementGuid>b9a6b548-c1e8-4600-a3c8-6423cd12b185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://pruebasqafenix.com/carrito/?cancel_order=true&amp;order=wc_order_SSjUnF0eJVNYf&amp;order_id=838&amp;redirect=https%3A%2F%2Fpruebasqafenix.com%2Fmi-cuenta%2F&amp;_wpnonce=be2c19371b')]</value>
      <webElementGuid>c1cf6cee-7aa3-4aee-a578-b1c637b3a086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>9185da29-9fa9-4351-9d79-361f930cd484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://pruebasqafenix.com/carrito/?cancel_order=true&amp;order=wc_order_SSjUnF0eJVNYf&amp;order_id=838&amp;redirect=https%3A%2F%2Fpruebasqafenix.com%2Fmi-cuenta%2F&amp;_wpnonce=be2c19371b' and (text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>7f7a2399-5e05-484b-b631-701bcfc9ad9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
