<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DireccionDeEnvioYFacturacion</name>
   <tag></tag>
   <elementGuidId>f7cdb258-6a04-4db9-8687-d7d77b324c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/p[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-MyAccount-content > p:nth-of-type(2) > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d479df41-1791-4b52-850a-ea209eba4567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/mi-cuenta/direccion/</value>
      <webElementGuid>2edf9a73-620b-44bb-bbe5-15200c34f4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>direcciones de envío y facturación</value>
      <webElementGuid>dc635173-767c-42fd-939a-a4f167407353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-464 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/p[2]/a[2]</value>
      <webElementGuid>4a7e3ba4-c1b3-4aa3-a0ed-d0af22621ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/p[2]/a[2]</value>
      <webElementGuid>c64b993b-93c6-4747-88f4-f25b221b19ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'direcciones de envío y facturación')]</value>
      <webElementGuid>e5687d27-022b-4a81-9fde-899962754be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pedidos recientes'])[1]/following::a[1]</value>
      <webElementGuid>a2df4824-5120-4d12-ade2-868e0f4e52ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/following::a[2]</value>
      <webElementGuid>032d87ff-d1bc-4eaa-a22c-b30a962384a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='editar tu contraseña y los detalles de tu cuenta'])[1]/preceding::a[1]</value>
      <webElementGuid>076a641e-30a7-4174-80e9-593d585b5692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscríbete al blog por correo electrónico'])[1]/preceding::a[2]</value>
      <webElementGuid>2744f21c-b63b-4976-8fba-961e25f23fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='direcciones de envío y facturación']/parent::*</value>
      <webElementGuid>047b9388-5cd4-4464-9b74-3bd938e22717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://pruebasqafenix.com/mi-cuenta/direccion/')])[2]</value>
      <webElementGuid>b7b373e4-628e-447f-9ea6-8716e6e277e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/p[2]/a[2]</value>
      <webElementGuid>c1dfb442-5a67-4868-b45f-afe1584ef5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://pruebasqafenix.com/mi-cuenta/direccion/' and (text() = 'direcciones de envío y facturación' or . = 'direcciones de envío y facturación')]</value>
      <webElementGuid>77c2a34c-0a74-4f8b-99e7-598e738758bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
