<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Darte de baja de nuestro boletn_mailc_aff7e8</name>
   <tag></tag>
   <elementGuidId>69d08e71-a6f0-474e-8056-c1eb52eb1913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailchimp_woocommerce_is_unsubscribed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mailchimp_woocommerce_is_unsubscribed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba513808-3091-4781-8232-61149dea7f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8fca9e6d-4106-4c18-a4a8-b2977e53a697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-radio input-radio</value>
      <webElementGuid>20bff5d5-abd9-4aba-8da7-f411aa37e273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_is_subscribed_radio</value>
      <webElementGuid>6bc3d71f-6909-4425-8a9c-ef4978a5d943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_is_unsubscribed</value>
      <webElementGuid>c9ae9aaa-09a9-4051-a795-1866614a4d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>unsubscribed</value>
      <webElementGuid>dbcf398f-1b82-4a11-aa35-15ec1e669c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>18b134b3-7321-4fc0-8454-5182138777b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailchimp_woocommerce_is_unsubscribed&quot;)</value>
      <webElementGuid>66995d70-2007-4758-9dc4-98b0e8087631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailchimp_woocommerce_is_unsubscribed']</value>
      <webElementGuid>da42563e-4745-4159-81bc-8b841068897c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/form/p[6]/label/input</value>
      <webElementGuid>5c9176b4-9dc1-4637-8397-4404579fa31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/label/input</value>
      <webElementGuid>7cbc267b-830e-40a3-8e9c-96d5e9df355c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'mailchimp_woocommerce_is_subscribed_radio' and @id = 'mailchimp_woocommerce_is_unsubscribed' and @checked = 'checked']</value>
      <webElementGuid>2e17fa41-43e0-4ae3-8967-b64ad78fb744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
