<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mailchimp_woocommerce_newsletter</name>
   <tag></tag>
   <elementGuidId>bab26cdd-81a5-46f8-bea5-3abb5afcd6ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailchimp_woocommerce_newsletter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mailchimp_woocommerce_newsletter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad390c8a-62ad-4d44-82f9-246e0aae475e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>716be861-db03-483c-a603-bccd6eca8eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_newsletter</value>
      <webElementGuid>9b3937db-20bd-4794-acb8-7a5f01ebe3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3a280be8-16cc-4313-8567-daf9ec79256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_newsletter</value>
      <webElementGuid>3914f791-2138-4683-afdb-032f96bbd9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>38c028a9-330e-4129-a473-306f23b202f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>3283a04e-dc19-4832-877b-8e2f87bcfdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailchimp_woocommerce_newsletter&quot;)</value>
      <webElementGuid>581c23ca-0d0a-4d80-8533-fc0a2b8de3c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailchimp_woocommerce_newsletter']</value>
      <webElementGuid>9f47c3a7-8694-4d1c-9b18-c749cbb9252d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/form/p[3]/label/input</value>
      <webElementGuid>1265203e-e65a-4dc4-9ca9-7f7f63161f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/p[3]/label/input</value>
      <webElementGuid>7187fc57-5d6e-457b-839b-0d446b90a876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mailchimp_woocommerce_newsletter' and @type = 'checkbox' and @name = 'mailchimp_woocommerce_newsletter' and @checked = 'checked']</value>
      <webElementGuid>6eec2177-6cef-4d50-aa52-9f361c87460b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
