<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suscrbete a nuestro boletn_mailchimp__5ffe50</name>
   <tag></tag>
   <elementGuidId>fc2ff578-134e-4180-8c7e-c07154afe6db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailchimp_woocommerce_is_subscribed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mailchimp_woocommerce_is_subscribed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c60c37d4-9c5f-4268-b081-f69fdbf64304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>55d4fff4-0d27-4bb5-9c1f-b21a0e95d0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-radio input-radio</value>
      <webElementGuid>69962aa7-5d58-48fa-addd-7d0b6d57c4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_is_subscribed_radio</value>
      <webElementGuid>0a431970-25a0-43c6-b5f2-845b46e0658f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_is_subscribed</value>
      <webElementGuid>ec1ed194-19ea-40ad-b274-533e6a9eeabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>559e9897-b8c1-48d8-92d1-d2a4bee53f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailchimp_woocommerce_is_subscribed&quot;)</value>
      <webElementGuid>a6d7672c-448d-4296-be09-817660fa8935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailchimp_woocommerce_is_subscribed']</value>
      <webElementGuid>9b1dde92-1ec9-4d7d-a5b1-698ec6bf8012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/form/p[5]/label/input</value>
      <webElementGuid>98c2bd25-dde7-4e98-a612-fea5d6fce5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>48d9dedd-0523-4318-9224-bb0464e1c16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'mailchimp_woocommerce_is_subscribed_radio' and @id = 'mailchimp_woocommerce_is_subscribed']</value>
      <webElementGuid>0cd2af00-c9a0-42b6-b296-d838f82d16a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
