<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nueva contrasea (djalo en blanco para_cd8deb</name>
   <tag></tag>
   <elementGuidId>d738a309-f73f-4980-94e2-ea7a1f6c193c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/form/fieldset/p[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ae4c08d6-a79e-4286-ada2-61c9e0e8c5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password_1</value>
      <webElementGuid>351283fa-3b9d-44d0-9a55-24fb7b5e14a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva contraseña (déjalo en blanco para no cambiarla)</value>
      <webElementGuid>aa56ebd7-8c5d-4249-979e-b512f14c9745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-464 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/form[@class=&quot;woocommerce-EditAccountForm edit-account&quot;]/fieldset[1]/p[@class=&quot;woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide&quot;]/label[1]</value>
      <webElementGuid>020a4348-3e26-4a01-b2d7-49acb69b7720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/form/fieldset/p[2]/label</value>
      <webElementGuid>aef21573-3b36-4021-8b76-f6793a102e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contraseña actual (déjalo en blanco para no cambiarla)'])[1]/following::label[1]</value>
      <webElementGuid>6ce6a534-dc23-419f-9def-889853d0be22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambio de contraseña'])[1]/following::label[2]</value>
      <webElementGuid>a3698ae0-2bd7-42b7-8198-1a63aef65a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar nueva contraseña (déjalo en blanco para no cambiarla)'])[1]/preceding::label[1]</value>
      <webElementGuid>b6399626-e3cd-4944-beb3-b7260055506b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscríbete a nuestro boletín'])[1]/preceding::label[2]</value>
      <webElementGuid>a77bada7-1744-4641-a5f2-9ff0634dfaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva contraseña (déjalo en blanco para no cambiarla)']/parent::*</value>
      <webElementGuid>bcaad777-8e04-40aa-b318-53426b62b416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/p[2]/label</value>
      <webElementGuid>89af2fd3-f103-4135-a63b-5144e49e8a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nueva contraseña (déjalo en blanco para no cambiarla)' or . = 'Nueva contraseña (déjalo en blanco para no cambiarla)')]</value>
      <webElementGuid>04c32991-2096-437b-9f93-e6b6776200be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
