<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Recibir actualizaciones de pedidos</name>
   <tag></tag>
   <elementGuidId>ef032721-2e89-47d1-a9f4-d0283f593e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/form/p[7]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>01d7659b-27d7-47b2-9ee1-77bc8afd675c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mailchimp_woocommerce_is_transactional</value>
      <webElementGuid>cd37ec53-ae69-404d-bd8c-18a9bd0c867e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recibir actualizaciones de pedidos</value>
      <webElementGuid>eb0032d4-05f7-4830-8912-e4f8f490e43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-464 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/form[@class=&quot;woocommerce-EditAccountForm edit-account&quot;]/p[@class=&quot;woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide&quot;]/label[1]</value>
      <webElementGuid>6eec8304-6b97-4d85-b6f8-a338f3a21d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div/form/p[7]/label</value>
      <webElementGuid>a538d899-9d47-46b6-8d92-0e8c81d6107e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Darte de baja de nuestro boletín'])[1]/following::label[1]</value>
      <webElementGuid>394fb534-4109-4689-86a5-61ac567ddc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscríbete a nuestro boletín'])[1]/following::label[2]</value>
      <webElementGuid>6bdbf8da-7373-4cc7-84d2-b47b8c4d983d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar los cambios'])[1]/preceding::label[1]</value>
      <webElementGuid>490a92d4-4c3d-47d9-85d5-97e998f8d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscríbete al blog por correo electrónico'])[1]/preceding::label[1]</value>
      <webElementGuid>1647517c-cf4a-478f-99ce-bdb40c6060f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recibir actualizaciones de pedidos']/parent::*</value>
      <webElementGuid>fe423c2b-de73-4f56-8aab-f72915399c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/label</value>
      <webElementGuid>f021d14a-c5d5-4551-b250-e6ec8b2d25b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Recibir actualizaciones de pedidos' or . = 'Recibir actualizaciones de pedidos')]</value>
      <webElementGuid>11c4eea2-88a9-4f42-be50-caf04f8f67bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
