<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Portada  Mi Cuenta</name>
   <tag></tag>
   <elementGuidId>22d68201-5ce6-420e-bc61-71bdaa850e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='breadcrumbs']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#breadcrumbs > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>07bd0795-3312-4f7e-80c1-b3b0e94a03cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portada » Mi Cuenta</value>
      <webElementGuid>d244c577-8147-4315-8501-86d34630c9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumbs&quot;)/span[1]</value>
      <webElementGuid>97ecb7b8-464c-462d-8130-9433fe7fee67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='breadcrumbs']/span</value>
      <webElementGuid>74168232-822c-4375-8df6-e656ec8e9381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas especiales'])[1]/following::span[1]</value>
      <webElementGuid>a7cbc834-0154-42a6-b3c6-103abacd2650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envio gratis'])[1]/following::span[1]</value>
      <webElementGuid>e971a434-842d-4a3a-86d8-a3d8d8e07985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='»']/parent::*</value>
      <webElementGuid>c0cf1176-3daf-480b-807e-7adaa72db7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>75f62527-9a01-4bd6-a660-1db448f9e325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Portada » Mi Cuenta' or . = 'Portada » Mi Cuenta')]</value>
      <webElementGuid>16955b89-6223-43f2-bbd8-ff602172ba0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
