<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Recurdame</name>
   <tag></tag>
   <elementGuidId>2632448b-68f3-4f4e-8ef2-7953bea6392e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_login']/div/form/p[3]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.woocommerce-form__label.woocommerce-form__label-for-checkbox.woocommerce-form-login__rememberme > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14933bdb-9e61-4604-af76-e1bda6407e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recuérdame</value>
      <webElementGuid>e3866b04-b0dc-4821-b1ff-e861bcb29ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;u-column1 col-1&quot;]/form[@class=&quot;woocommerce-form woocommerce-form-login login&quot;]/p[@class=&quot;form-row&quot;]/label[@class=&quot;woocommerce-form__label woocommerce-form__label-for-checkbox woocommerce-form-login__rememberme&quot;]/span[1]</value>
      <webElementGuid>2cc91433-d335-497f-8190-749230ea56cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div/form/p[3]/label/span</value>
      <webElementGuid>32152683-be4e-42c9-8b3c-948f5c35ceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[3]</value>
      <webElementGuid>3c93f738-8a29-4e68-be88-220c8c7f072c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acceder'])[2]/preceding::span[1]</value>
      <webElementGuid>13c90c5a-30ff-40a0-884d-72c4313c12e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste la contraseña?'])[1]/preceding::span[1]</value>
      <webElementGuid>92153ba7-c4e7-40d1-a66f-0d0bc3260f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recuérdame']/parent::*</value>
      <webElementGuid>2f48692f-7e2a-4663-8574-2e90ae121c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/label/span</value>
      <webElementGuid>845d099b-4974-4a6d-9326-5f8eecb2bf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Recuérdame' or . = 'Recuérdame')]</value>
      <webElementGuid>94667a57-2342-4574-94bb-c64d6b284806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
