<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Finalizar compra</name>
   <tag></tag>
   <elementGuidId>6e45cdb2-1104-4d09-aaef-0a6431a1079c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='blog']/div[2]/div/div/div/div[4]/div/div/div/ul/li/div/div/p[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.checkout.wc-forward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7f4d06e-faa8-47c2-826e-af6af35539ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/checkout/</value>
      <webElementGuid>58721832-7aba-4c54-8e45-2b2e5d107ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button checkout wc-forward</value>
      <webElementGuid>cb0ed6f2-238e-4568-b6dd-9fb0e306217c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar compra</value>
      <webElementGuid>776efb76-41d2-42e3-afec-70966c3137b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog&quot;)/div[@class=&quot;page-wrap&quot;]/div[@class=&quot;site-header container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;heading-row row&quot;]/div[@class=&quot;header-right col-md-3&quot;]/div[@class=&quot;header-cart&quot;]/div[@class=&quot;header-cart-block&quot;]/div[@class=&quot;header-cart-inner&quot;]/ul[@class=&quot;site-header-cart menu list-unstyled text-center&quot;]/li[1]/div[@class=&quot;widget woocommerce widget_shopping_cart&quot;]/div[@class=&quot;widget_shopping_cart_content&quot;]/p[@class=&quot;woocommerce-mini-cart__buttons buttons&quot;]/a[@class=&quot;button checkout wc-forward&quot;]</value>
      <webElementGuid>6e7f33d9-a9ce-4bde-bba2-9a7b6f43e402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='blog']/div[2]/div/div/div/div[4]/div/div/div/ul/li/div/div/p[2]/a[2]</value>
      <webElementGuid>40fe69cc-4028-4312-ae94-34a671963e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Finalizar compra')]</value>
      <webElementGuid>761aa9a4-31be-402a-a4c8-6a5f9b3bf6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver carrito'])[1]/following::a[1]</value>
      <webElementGuid>2447a5da-7f0c-471c-8526-9a0aa202173a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[3]/following::a[2]</value>
      <webElementGuid>3a177df3-353d-48e2-adda-1a37fa058148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menú'])[1]/preceding::a[4]</value>
      <webElementGuid>fa3f4bcc-4ddd-47dc-b006-f1cd40f5c88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::a[5]</value>
      <webElementGuid>43291a81-f2f0-4961-bdfe-319f4ba7b71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar compra']/parent::*</value>
      <webElementGuid>15bec6b1-042a-4494-8925-36e14fd81b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://pruebasqafenix.com/checkout/')]</value>
      <webElementGuid>0bd115d9-14bf-479d-a095-7dddd6bcf224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a[2]</value>
      <webElementGuid>7fd2834d-3f88-4a74-bb53-501dd142e546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://pruebasqafenix.com/checkout/' and (text() = 'Finalizar compra' or . = 'Finalizar compra')]</value>
      <webElementGuid>1ee4d153-ff05-4e7a-8e13-3ed5867c6823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
