<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PrecioTotalCarrito</name>
   <tag></tag>
   <elementGuidId>0ed981e2-2360-4292-9431-a387a64f9036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='blog']/div[2]/div/div/div/div[4]/div/div/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.amount-cart.hidden-xs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cb3aae7-636b-4013-9888-6cc9bd878c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>amount-cart hidden-xs</value>
      <webElementGuid>32e2400d-1392-468b-895c-ba0ac80ca878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>81,00 €</value>
      <webElementGuid>ec72af10-cb4d-4cd8-9bde-9ee4ed86e8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog&quot;)/div[@class=&quot;page-wrap&quot;]/div[@class=&quot;site-header container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;heading-row row&quot;]/div[@class=&quot;header-right col-md-3&quot;]/div[@class=&quot;header-cart&quot;]/div[@class=&quot;header-cart-block&quot;]/div[@class=&quot;header-cart-inner&quot;]/a[@class=&quot;cart-contents&quot;]/div[@class=&quot;amount-cart hidden-xs&quot;]</value>
      <webElementGuid>0ae2a586-7638-41dc-a161-4c3a244c76ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='blog']/div[2]/div/div/div/div[4]/div/div/div/a/div</value>
      <webElementGuid>0fd89301-f13a-46e9-95c2-a6f3c6c8a9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saltar al contenido'])[1]/following::div[16]</value>
      <webElementGuid>2f7ea100-d5d7-44c5-98f8-141ce4d10362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::div[1]</value>
      <webElementGuid>e13391de-456a-4350-b29e-d88b2e038d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='81,00 €']/parent::*</value>
      <webElementGuid>1e373dc1-2c6a-4308-833d-027d50b03502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>07a77b03-998d-42bb-adbb-bbf3dc362ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '81,00 €' or . = '81,00 €')]</value>
      <webElementGuid>5319e5ba-7552-4987-8f07-6fa85b2593f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
