<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconoCarrito</name>
   <tag></tag>
   <elementGuidId>83a79ea1-f0d5-4707-bb64-40d1913a173c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='blog']/div[2]/div/div/div/div[4]/div/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.la.la-shopping-bag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b27ceab1-3395-430c-8bb3-ebfb1a409bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>la la-shopping-bag</value>
      <webElementGuid>3da025f2-b686-429a-a0d3-0479c1e29328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a050748b-b8b5-4f63-b788-de6ebed96694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog&quot;)/div[@class=&quot;page-wrap&quot;]/div[@class=&quot;site-header container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;heading-row row&quot;]/div[@class=&quot;header-right col-md-3&quot;]/div[@class=&quot;header-cart&quot;]/div[@class=&quot;header-cart-block&quot;]/div[@class=&quot;header-cart-inner&quot;]/a[@class=&quot;cart-contents&quot;]/i[@class=&quot;la la-shopping-bag&quot;]</value>
      <webElementGuid>19a834e5-e2da-4100-83f0-e7664400792b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='blog']/div[2]/div/div/div/div[4]/div/div/div/a/i</value>
      <webElementGuid>1fe30488-8a0f-4f81-899c-f335e336d0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saltar al contenido'])[1]/following::i[1]</value>
      <webElementGuid>7e07a482-2223-4025-ad28-5eaaf950b632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::i[1]</value>
      <webElementGuid>88b41cf3-82e8-478e-9884-48ba0d35d31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>1f942342-b932-4432-ba48-d54c55bd2519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '1' or . = '1')]</value>
      <webElementGuid>f1260662-3242-41a1-86eb-859b777cbeba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
