<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Direccin de correo electrnico</name>
   <tag></tag>
   <elementGuidId>cbfb58b9-574d-4de5-971f-a60c99602817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_email_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_email_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f51664a1-f2ac-4214-8cf8-97b87144a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_email</value>
      <webElementGuid>b64dc456-5ddd-4308-8eb5-0261b7da7472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dirección de correo electrónico *</value>
      <webElementGuid>1f2ec276-dfc6-49c1-a93d-81b218de4ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_email_field&quot;)/label[1]</value>
      <webElementGuid>74c7e8ce-388c-44c2-8154-f6892fa55e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_email_field']/label</value>
      <webElementGuid>cad72f84-1d88-4769-aef3-4fd428acdd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::label[1]</value>
      <webElementGuid>08f6458e-fac5-45c9-9645-163876c5963c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscríbete a nuestro boletín'])[1]/preceding::label[1]</value>
      <webElementGuid>6d758d04-aea2-4b48-8c09-553df2ed947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/label</value>
      <webElementGuid>4bfbfb48-1629-4ef4-8c88-975217d4a0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Dirección de correo electrónico *' or . = 'Dirección de correo electrónico *')]</value>
      <webElementGuid>c7e52b0f-3c7f-4194-82b5-3356c06b1dd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
