<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CalcularEnvio</name>
   <tag></tag>
   <elementGuidId>be66fb2f-3307-4c7b-9c55-dd811963a0a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/div[4]/div/table/tbody/tr[2]/td/form/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.shipping-calculator-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e2e6ebd-c957-4c12-8b7e-d4e10bb602fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c466ccfd-fbf2-4b1b-93eb-4f84cd7c5be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shipping-calculator-button</value>
      <webElementGuid>81527564-7435-46cb-b69f-0bedf1489337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calcular envío</value>
      <webElementGuid>2b40327e-2c3f-465d-b142-74dd2eab9fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;cart-collaterals&quot;]/div[@class=&quot;cart_totals&quot;]/table[@class=&quot;shop_table shop_table_responsive&quot;]/tbody[1]/tr[@class=&quot;woocommerce-shipping-totals shipping&quot;]/td[1]/form[@class=&quot;woocommerce-shipping-calculator&quot;]/a[@class=&quot;shipping-calculator-button&quot;]</value>
      <webElementGuid>34a4b12f-aaea-4be1-b565-9e1a4d8b0bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div[4]/div/table/tbody/tr[2]/td/form/a</value>
      <webElementGuid>a7ef5d6a-6d1b-4da9-8d3f-cac39b090cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Calcular envío')]</value>
      <webElementGuid>0afced15-fc2c-4c7f-a6ec-25d6908551f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[14]/following::a[1]</value>
      <webElementGuid>5fa202cd-ff48-43a9-87cf-c14bad8af271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País o región:'])[1]/preceding::a[1]</value>
      <webElementGuid>b84356f0-cba0-4b06-bbd8-16c0b2f210f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calcular envío']/parent::*</value>
      <webElementGuid>a45339b7-7da7-497b-8059-a45a5e89bd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>3d065df3-5bef-4275-b0f2-17a97cd730b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>4ab0e10f-b85c-4de8-a3e7-430ebb54f1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Calcular envío' or . = 'Calcular envío')]</value>
      <webElementGuid>7c55c059-50ad-441a-ba1b-40af1c45adcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
