<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cabecera_Carrito</name>
   <tag></tag>
   <elementGuidId>0b5796b0-1026-4d88-826b-d92968be23d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/header/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.single-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>641cb5f9-f372-4cbe-9ef7-7fa9cd3acfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-title</value>
      <webElementGuid>212c702c-b773-4e85-a47c-74d156662366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carrito</value>
      <webElementGuid>130c3484-3ed8-41a6-b6f6-ec733503de71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/header[@class=&quot;single-head page-head no-thumbnail&quot;]/h1[@class=&quot;single-title&quot;]</value>
      <webElementGuid>f3e092ea-a484-48c9-b599-a91e489671b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/header/h1</value>
      <webElementGuid>dce1d6c8-0840-4c80-a9d7-8ad77a59c35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrito'])[1]/following::h1[1]</value>
      <webElementGuid>9f089767-e55b-4485-97ca-14c2164a095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portada'])[1]/following::h1[1]</value>
      <webElementGuid>f92d2f9e-c8cb-4efd-9a90-19bce5445c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplicar tarjeta regalo'])[1]/preceding::h1[1]</value>
      <webElementGuid>282cf606-43df-4c45-ba9c-2bb41d8ae895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>43b30b9e-5226-4a45-82bb-f1de6d846bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Carrito' or . = 'Carrito')]</value>
      <webElementGuid>9917692d-901b-45c8-b50d-d074a9a388f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
