<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cantidad_Pantalon y camisa de hombre</name>
   <tag></tag>
   <elementGuidId>380ee5ac-faaa-421f-b72e-5b83b02f409a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_64a2e0389affe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity_64a2e0389affe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0850579f-635c-4666-ab69-717b238d0896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ad420d42-e594-4df9-80b8-e503baa862dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_64a2e0389affe</value>
      <webElementGuid>ea89d46b-2c14-4396-b770-c7815ec49ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>ab50f53f-411b-49b2-a992-622d809f4657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[cbcb58ac2e496207586df2854b17995f][qty]</value>
      <webElementGuid>c60849b1-1fee-4fb9-ac5a-f154330c1805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>80bab07e-4049-4abe-906d-7b177928ab99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cantidad de productos</value>
      <webElementGuid>a09a622a-370c-4aba-b504-90b6c2ac3d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c9ff4940-10d9-4c87-b26f-a5ef9abf0b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0762d617-23db-479e-9146-f4c395f86b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9db2e331-1572-4c38-a389-22d3ce4f7d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>6bbfa0e5-b667-44e4-af7d-2b3932210d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f6331ba-31ba-4100-a376-124a32456107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_64a2e0389affe&quot;)</value>
      <webElementGuid>f8dc34d8-f70b-48f5-b655-af6945157815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_64a2e0389affe']</value>
      <webElementGuid>acecf441-37fd-46f4-a538-ca658a310b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>e429c7b3-db35-42b6-9017-3f5916982ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>95b55485-9261-424f-97d3-939f11fa82db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_64a2e0389affe' and @name = 'cart[cbcb58ac2e496207586df2854b17995f][qty]']</value>
      <webElementGuid>a3024061-0b0c-46ad-b2e5-963bdcc4e10f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
