<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_5f269b_1_2</name>
   <tag></tag>
   <elementGuidId>9457c7f4-c84f-4342-8e87-cf42cba0bd57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr[3]/td[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7761da73-8332-4342-b736-8aea8997c867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>3859f903-6917-46d2-a970-690f5398b2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>06ad07aa-ca33-4f1f-bccb-45b241eb06fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-300x450.jpg</value>
      <webElementGuid>b93a3564-e33a-46b2-9ea9-8ed9789b8747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>c126569a-219f-4c6e-acf0-1f2741377b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>39d98ee7-e967-4330-81c7-356f169da2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-300x450.jpg.webp 300w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-600x900.jpg.webp 600w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-200x300.jpg.webp 200w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-682x1024.jpg.webp 682w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-768x1152.jpg.webp 768w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-40x60.jpg.webp 40w, https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280.jpg.webp 853w</value>
      <webElementGuid>d5ccbb73-7979-40dd-9f1d-40aadfee954b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>69197990-d60b-42b0-b701-a560b08bb94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-384 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-thumbnail&quot;]/a[1]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>0cf22d81-1a8e-47e3-b393-6b3069f2cbec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/form/table/tbody/tr[3]/td[2]/a/img</value>
      <webElementGuid>e17aa110-8267-49c4-87bb-409651308a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-300x450.jpg')]</value>
      <webElementGuid>f93fc1f2-b1b6-4795-afe7-1520db0db9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/a/img</value>
      <webElementGuid>b187cd1c-8642-46dc-9dcb-10e04f2d7c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pruebasqafenix.com/wp-content/uploads/2021/07/girl-3713105_1280-300x450.jpg']</value>
      <webElementGuid>f9dd051e-f518-4d31-b43a-2dfcdc21aa21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
