<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Precio fijo 3,00</name>
   <tag></tag>
   <elementGuidId>a7a44834-fec5-4d0b-a953-63bc5781b2dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='shipping_method']/li/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3dbbf6fe-0862-4f76-a3d6-445f5ac53bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>shipping_method_0_flat_rate2</value>
      <webElementGuid>a97b9582-59a1-482a-9972-09e9a138504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Precio fijo: 3,00 €</value>
      <webElementGuid>c724cae9-f386-439e-9f57-bb326c06fbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping_method&quot;)/li[1]/label[1]</value>
      <webElementGuid>507017a5-f6e3-4e5e-9599-e99d65138a31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='shipping_method']/li/label</value>
      <webElementGuid>6cbc3116-c6f4-4f8a-a60f-844eecb1ecba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envío'])[1]/following::label[1]</value>
      <webElementGuid>f12b254f-3378-45cc-ae93-154aafe9f93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[13]/following::label[1]</value>
      <webElementGuid>9cc83a8a-e387-473d-bfbd-bfee9f68a8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País o región:'])[1]/preceding::label[1]</value>
      <webElementGuid>5ca0507a-2f10-406e-bd75-91eafbdcce6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Precio fijo:']/parent::*</value>
      <webElementGuid>795b020e-9608-4fdf-a289-4b949e4623fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/label</value>
      <webElementGuid>381d9144-3a88-4768-a924-387a399a61c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Precio fijo: 3,00 €' or . = 'Precio fijo: 3,00 €')]</value>
      <webElementGuid>babb19db-c56d-4670-90f6-b8b2f6f697d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
